// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        int32            `db:"id" json:"id"`
	UserID    int32            `db:"user_id" json:"user_id"`
	Total     pgtype.Numeric   `db:"total" json:"total"`
	Status    string           `db:"status" json:"status"`
	Address   string           `db:"address" json:"address"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type OrderItem struct {
	ID        int32          `db:"id" json:"id"`
	OrderID   int32          `db:"order_id" json:"order_id"`
	ProductID int32          `db:"product_id" json:"product_id"`
	Quantity  int32          `db:"quantity" json:"quantity"`
	Price     pgtype.Numeric `db:"price" json:"price"`
}

type Product struct {
	ID          int32            `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description string           `db:"description" json:"description"`
	Image       string           `db:"image" json:"image"`
	Price       pgtype.Numeric   `db:"price" json:"price"`
	Quantity    int32            `db:"quantity" json:"quantity"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type User struct {
	ID        int32            `db:"id" json:"id"`
	Firstname string           `db:"firstname" json:"firstname"`
	Lastname  string           `db:"lastname" json:"lastname"`
	Email     string           `db:"email" json:"email"`
	Password  string           `db:"password" json:"password"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}
