// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int32         `db:"id" json:"id"`
	NovelID   int32         `db:"novel_id" json:"novel_id"`
	UserID    int32         `db:"user_id" json:"user_id"`
	ParentID  sql.NullInt32 `db:"parent_id" json:"parent_id"`
	Content   string        `db:"content" json:"content"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
}

type CommentLike struct {
	ID        int32     `db:"id" json:"id"`
	CommentID int32     `db:"comment_id" json:"comment_id"`
	UserID    int32     `db:"user_id" json:"user_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Novel struct {
	ID        int32     `db:"id" json:"id"`
	Title     string    `db:"title" json:"title"`
	Keyword   string    `db:"keyword" json:"keyword"`
	Short     string    `db:"short" json:"short"`
	Content   string    `db:"content" json:"content"`
	UserID    int32     `db:"user_id" json:"user_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type NovelLike struct {
	ID        int32     `db:"id" json:"id"`
	NovelID   int32     `db:"novel_id" json:"novel_id"`
	UserID    int32     `db:"user_id" json:"user_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type NovelTag struct {
	NovelID int32 `db:"novel_id" json:"novel_id"`
	TagID   int32 `db:"tag_id" json:"tag_id"`
}

type Tag struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type User struct {
	ID        int32     `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Email     string    `db:"email" json:"email"`
	Password  string    `db:"password" json:"password"`
	Role      string    `db:"role" json:"role"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
